export const properties = [
  {
    name: 'align-content',
  }, {
    name: 'align-items',
  }, {
    name: 'align-self',
  }, {
    name: 'all',
  }, {
    name: 'animation',
  }, {
    name: 'animation-delay',
  }, {
    name: 'animation-direction',
  }, {
    name: 'animation-duration',
  }, {
    name: 'animation-fill-mode',
  }, {
    name: 'animation-iter-count',
  }, {
    name: 'animation-name'
  }, {
    name: 'animation-play-state'
  }, {
    name: 'animation-timing-fn'
  }, {
    name: 'backface-visibility'
  }, {
    name: 'background'
  }, {
    name: 'background-attachment'
  }, {
    name: 'background-blend-mode'
  }, {
    name: 'background-clip'
  }, {
    name: 'background-color'
  }, {
    name: 'background-image'
  }, {
    name: 'background-origin'
  }, {
    name: 'background-position'
  }, {
    name: 'background-repeat'
  }, {
    name: 'background-size'
  }, {
    name: 'border'
  }, {
    name: 'border-bottom'
  }, {
    name: 'border-bottom-color'
  }, {
    name: 'border-bottom-left-rad'
  }, {
    name: 'border-bottom-right-ra'
  }, {
    name: 'border-bottom-style'
  }, {
    name: 'border-bottom-width'
  }, {
    name: 'border-collapse'
  }, {
    name: 'border-color'
  }, {
    name: 'border-image'
  }, {
    name: 'border-image-outset'
  }, {
    name: 'border-image-repeat'
  }, {
    name: 'border-image-slice'
  }, {
    name: 'border-image-source'
  }, {
    name: 'border-image-width'
  }, {
    name: 'border-left'
  }, {
    name: 'border-left-color'
  }, {
    name: 'border-left-style'
  }, {
    name: 'border-left-width'
  }, {
    name: 'border-radius'
  }, {
    name: 'border-right'
  }, {
    name: 'border-right-color'
  }, {
    name: 'border-right-style'
  }, {
    name: 'border-right-width'
  }, {
    name: 'border-spacing'
  }, {
    name: 'border-style'
  }, {
    name: 'border-top'
  }, {
    name: 'border-top-color'
  }, {
    name: 'border-top-left-radius'
  }, {
    name: 'border-top-right-radiu'
  }, {
    name: 'border-top-style'
  }, {
    name: 'border-top-width'
  }, {
    name: 'border-width'
  }, {
    name: 'bottom'
  }, {
    name: 'box-decoration-break'
  }, {
    name: 'box-shadow'
  }, {
    name: 'box-sizing'
  }, {
    name: 'caption-side'
  }, {
    name: 'caret-color'
  }, {
    name: '@charset'
  }, {
    name: 'clear'
  }, {
    name: 'clip'
  }, {
    name: 'clip-path'
  }, {
    name: 'color'
  }, {
    name: 'column-count'
  }, {
    name: 'column-fill'
  }, {
    name: 'column-gap'
  }, {
    name: 'column-rule'
  }, {
    name: 'column-rule-color'
  }, {
    name: 'column-rule-style'
  }, {
    name: 'column-rule-width'
  }, {
    name: 'column-span'
  }, {
    name: 'column-width'
  }, {
    name: 'columns'
  }, {
    name: 'content'
  }, {
    name: 'counter-increment'
  }, {
    name: 'counter-reset'
  }, {
    name: 'cursor'
  }, {
    name: 'direction'
  }, {
    name: 'display'
  }, {
    name: 'empty-cells'
  }, {
    name: 'filter'
  }, {
    name: 'flex'
  }, {
    name: 'flex-basis'
  }, {
    name: 'flex-direction'
  }, {
    name: 'flex-flow'
  }, {
    name: 'flex-grow'
  }, {
    name: 'flex-shrink'
  }, {
    name: 'flex-wrap'
  }, {
    name: 'float'
  }, {
    name: 'font'
  }, {
    name: '@font-face'
  }, {
    name: 'font-family'
  }, {
    name: 'font-kerning'
  }, {
    name: 'font-size'
  }, {
    name: 'font-stretch'
  }, {
    name: 'font-style'
  }, {
    name: 'font-variant'
  }, {
    name: 'font-weight'
  }, {
    name: 'gap'
  }, {
    name: 'grid'
  }, {
    name: 'grid-area'
  }, {
    name: 'grid-auto-columns'
  }, {
    name: 'grid-auto-flow'
  }, {
    name: 'grid-auto-rows'
  }, {
    name: 'grid-column'
  }, {
    name: 'grid-column-end'
  }, {
    name: 'grid-column-gap'
  }, {
    name: 'grid-column-start'
  }, {
    name: 'grid-gap'
  }, {
    name: 'grid-row'
  }, {
    name: 'grid-row-end'
  }, {
    name: 'grid-row-gap'
  }, {
    name: 'grid-row-start'
  }, {
    name: 'grid-template'
  }, {
    name: 'grid-template-areas'
  }, {
    name: 'grid-template-columns'
  }, {
    name: 'grid-template-rows'
  }, {
    name: 'height'
  }, {
    name: 'hyphens'
  }, {
    name: '@import'
  }, {
    name: 'justify-content'
  }, {
    name: '@keyframes'
  }, {
    name: 'left'
  }, {
    name: 'letter-spacing'
  }, {
    name: 'line-height'
  }, {
    name: 'list-style'
  }, {
    name: 'list-style-image'
  }, {
    name: 'list-style-position'
  }, {
    name: 'list-style-type'
  }, {
    name: 'margin'
  }, {
    name: 'margin-bottom'
  }, {
    name: 'margin-left'
  }, {
    name: 'margin-right'
  }, {
    name: 'margin-top'
  }, {
    name: 'max-height'
  }, {
    name: 'max-width'
  }, {
    name: '@media'
  }, {
    name: 'min-height'
  }, {
    name: 'min-width'
  }, {
    name: 'object-fit'
  }, {
    name: 'object-position'
  }, {
    name: 'opacity'
  }, {
    name: 'order'
  }, {
    name: 'outline'
  }, {
    name: 'outline-color'
  }, {
    name: 'outline-offset'
  }, {
    name: 'outline-style'
  }, {
    name: 'outline-width'
  }, {
    name: 'overflow'
  }, {
    name: 'overflow-x'
  }, {
    name: 'overflow-y'
  }, {
    name: 'padding'
  }, {
    name: 'padding-bottom'
  }, {
    name: 'padding-left'
  }, {
    name: 'padding-right'
  }, {
    name: 'padding-top'
  }, {
    name: 'page-break-after'
  }, {
    name: 'page-break-before'
  }, {
    name: 'page-break-inside'
  }, {
    name: 'perspective'
  }, {
    name: 'perspective-origin'
  }, {
    name: 'pointer-events'
  }, {
    name: 'position'
  }, {
    name: 'quotes'
  }, {
    name: 'right'
  }, {
    name: 'row-gap'
  }, {
    name: 'scroll-behavior'
  }, {
    name: 'table-layout'
  }, {
    name: 'text-align'
  }, {
    name: 'text-align-last'
  }, {
    name: 'text-decoration'
  }, {
    name: 'text-decoration-color'
  }, {
    name: 'text-decoration-line'
  }, {
    name: 'text-decoration-style'
  }, {
    name: 'text-indent'
  }, {
    name: 'text-justify'
  }, {
    name: 'text-overflow'
  }, {
    name: 'text-shadow'
  }, {
    name: 'text-transform'
  }, {
    name: 'top'
  }, {
    name: 'transform'
  }, {
    name: 'transform-origin'
  }, {
    name: 'transform-style'
  }, {
    name: 'transition'
  }, {
    name: 'transition-delay'
  }, {
    name: 'transition-duration'
  }, {
    name: 'transition-property'
  }, {
    name: 'transition-timing-fn'
  }, {
    name: 'user-select'
  }, {
    name: 'vertical-align'
  }, {
    name: 'visibility'
  }, {
    name: 'white-space'
  }, {
    name: 'width'
  }, {
    name: 'word-break'
  }, {
    name: 'word-spacing'
  }, {
    name: 'word-wrap'
  }, {
    name: 'writing-mode'
  }, {
    name: 'z-index'
  }
]